graph:
  edges:
    barabasi:
      start: 1
      end: 10
    erdos:
      start: 0.0
      end: 1.0 
    fire:
      start: 0.0
      end: 1.0 
    geometric:
      start: 0.0
      end: 1.0
  nodes:
    start: 50
    end: 250
    step: 50
embedding:
  train:
    batch_size: 128
    steps_per_epoch: 1024
    epochs: 20 
  model:
    dim:
      start: 2 
      end: 51
